---
title: "Untitled"
author: "Abel Sapirstein"
date: "12/10/2021"
output: html_notebook
---

```{r setup, include=FALSE}
library(tidyverse)
source("likelihood.R")
library(purrr)
exp_params_test = readRDS("6state_exp_data_phylo_test.rds")
```

## Read in Cassiopeia Trees and Others for Comparison:

```{r cass}
tree_num <- 4 
j<- "0004"
"../Python/outputs/"
cass_dir = "../Python/outputs/"
cass_tree <- ape::read.tree(paste0(cass_dir,"cassiopeia",str_pad(tree_num, 4, pad = "0"), "_recon.txt"))
hybrid_no_prior  <- ape::read.tree(paste0("../6state_exp_test_data/trees/",j, "_hybrid_noprior.txt"))
truth  <- ape::read.tree(paste0("../6state_exp_test_data/trees/",j, "_truth.txt"))
hybrid_mutp  <- ape::read.tree(paste0("../6state_exp_test_data/trees/",j, "_hybrid_mutp.txt"))
phylip  <- ape::read.tree(paste0("../6state_exp_test_data/trees/",j, "_phylip.txt"))

a <- rbind( data.frame(evalute_gr(cass_tree , exp_params_test$tr[[tree_num]])),
            data.frame(evalute_gr(hybrid_mutp , exp_params_test$tr[[tree_num]])),
            data.frame(evalute_gr(hybrid_no_prior , exp_params_test$tr[[tree_num]])),
            data.frame(evalute_gr(phylip , exp_params_test$tr[[tree_num]])),
            data.frame(evalute_gr(truth , exp_params_test$tr[[tree_num]])))
a$mode <- c("Cassiopeia", "Hybrid Prior", "Hybrid No Prior", "Phylip", "Truth")
```

## Reading In Our Generated Trees:


```{r cell_phy}
tr = exp_params_test$tr[[j]]
tr_r = exp_params_test$tr3[[j]]
sc_mat = exp_params_test$sc[[j]]
mut_p = exp_params_test$mut_p[[j]]
total_time = 12.5
root_edge_len = 0.6
tree_data = make_tree_data(tr, sc_mat, rownames(sc_mat), total_time, root_edge_len)
tree_data = compute_allele_prob(tree_data, mut_p$recur_vec_list)
compute_loglike(tree_data, mut_p$mut_rate)
tree_data = make_tree_data(tr_r, sc_mat, rownames(sc_mat), total_time, root_edge_len)
tree_data = compute_allele_prob(tree_data, mut_p$recur_vec_list)
parentDirectory <- "../Python/outputs/marcc/oct_25/"
suffix <- "__sprmh_nsmh_random16999999"
```

```{r}
x_df_all_mh = bind_rows(map(c(1:3,5:11), function(i) {
        print(i)
        x_df = read_csv(paste0(parentDirectory, str_pad(tree_num, 4, pad = "0"), "/chain", i, suffix, ".csv"))
        x_df$chain = i
        x_df$index <- as.numeric(row.names(x_df))
        tree_dir = paste0(parentDirectory,str_pad(tree_num, 4, pad = "0"), "/trees/")

        tree_chain_files = list.files(tree_dir, patt = paste0("chain", i, "_tree.*",suffix))
        tree_index = str_replace(tree_chain_files, paste0("chain", i, "_tree"), "")
        tree_index = as.numeric(str_replace(tree_index, paste0(suffix,".txt"), ""))
        tree_chain = paste0(tree_dir, tree_chain_files) %>% map(ape::read.tree)
        names(tree_chain) <- paste0("chain",i,"iteration",tree_index)
        x_df$tr = tree_chain[match(x_df$index, tree_index)]
        x_df = mutate(x_df, tr_update = !map_lgl(tr, is.null))
        x_df = mutate(x_df, LL = map_dbl(tr, function(x) {
                if (!is.null(x)) {
                        tree_data = make_tree_data(x,
                                                   sc_mat,
                                                   rownames(sc_mat), total_time, root_edge_len)
                        tree_data = compute_allele_prob(tree_data, mut_p$recur_vec_list)
                        return(compute_loglike(tree_data, mut_p$mut_rate))

                }
                else return(NA)
        }))
        x_df = mutate(x_df, tr_eval = purrr::map(tr, function(y) {
                if (!is.null(y)) {
                        return(evalute_gr(y, exp_params_test$tr[[j]]))
                } else {
                        return(NULL)
                }
        }))
        x_df = mutate(x_df, rf = map_dbl(tr_eval, function(x) {
                if (!is.null(x)) return(x$rf)
                else return(NA)
        }))
        x_df = mutate(x_df, kc0 = map_dbl(tr_eval, function(x) {
                if (!is.null(x)) return(x$kc0)
                else return(NA)
        }))
        x_df = mutate(x_df, kc1 = map_dbl(tr_eval, function(x) {
                if (!is.null(x)) return(x$kc1)
                else return(NA)
        }))
        x_df
}))

        x_df_all_mh = mutate(x_df_all_mh, treevec_cor = map_dbl(tr_eval, function(x) {
                if (!is.null(x)) return(x$treevec_cor)
                else return(NA)}))
```
```{r} 
df <- x_df_all_mh %>% filter(tr_update == 1)%>% select(kc0,kc1, rf, treevec_cor) %>% mutate(mode = "Cell Phylo Likelihood")
df <- rbind(a,df)
```

# Chunks to get consensus trees: 
```{r} 
x_df_

```



```{r}
ggplot(df %>% filter(mode == "Cell Phylo Likelihood"),aes(x = kc0 , y = rf, color = mode))+geom_point() + geom_point(data=df %>% filter(mode != "Cell Phylo Likelihood" & kc0>0), aes(x = kc0, y = rf, color = mode ), size = 5) + ggtitle("Sample Tree of 150 Nodes") + xlab("KC 0 Distance") + ylab("RF Distance")

```

```{r}
ggplot(df %>% filter(mode == "Cell Phylo Likelihood"),aes(x = kc0 , y = kc1, color = mode))+geom_point() + geom_point(data=df %>% filter(mode != "Cell Phylo Likelihood" & mode != "Cassiopeia" & kc0>0), aes(x = kc0, y = kc1, color = mode ), size = 5) + ggtitle("Sample Tree of 150 Nodes") + xlab("KC 0 Distance") + ylab("KC 1 Distance")
```
